name: Secret Scanning

on:
  pull_request:
    branches: [ "trunk" ]

permissions:
  pull-requests: write

jobs:
  scan-for-secrets:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Scan for Secrets
        uses: secret-scanner/action@0.0.2
      - name: Greet from custom Docker action
        id: hello
        uses: ./.github/actions
        with:
          your_name: dmc
      - name: Get the output message
        run: echo "::debug::${{ steps.hello.outputs.message }}"
      - name: Comment on Pull Request
        run: gh pr comment ${{ github.event.pull_request.html_url }} --body "Repository scanned for exposed secrets!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}