name: Checking for Secrets
on:
  pull_request:
    types: [opened]
    branches: [ "trunk" ]
  repository_dispatch:
    types: [opened]
permissions:
  pull_requests: write
jobs:
  check-secrets:
    name: Checking for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
      - run: gh pr comment $PR_URL --body "Repository scanned for exposed secrets!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
