name: Add labels to PR
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: gh pr edit ${{ github.event.pull_request.number }} --add-label "approved"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}