name: Run tests in a Matrix
on:
  workflow_call:
    inputs:
      persist_users:
        description: "Persist test users in database"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      persist_users:
        description: "Persist test users in database"
        required: false
        default: false
        type: boolean

env:
  CYPRESS_PERSIST_USERS: ${{ inputs.persist_users }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox, edge, chrome]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: windows-latest
            browser: firefox
          - platform: ubuntu-latest
            browser: edge
          - platform: macos-latest
            browser: firefox
          - platform: macos-latest
            browser: edge
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - name: Running on Platform = ${{ matrix.platform }} Browser = ${{ matrix.browser }}
      run: npx cypress run --browser ${{ matrix.browser }}
    - name: Archive users.json
      if: inputs.persist_users
      uses: actions/upload-artifact@v3
      with:
        name: newCreatedUsers-${{ matrix.platform }}-${{ matrix.browser }}
        path: users.txt