name: Matrix with Cypress
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        browser: [firefox, edge, chrome]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: windows-latest
            browser: chrome
          - platform: ubuntu-latest
            browser: firefox
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - name: Running on Platform = ${{ matrix.platform }} Browser = ${{ matrix.browser }}
      run: npx cypress run --browser ${{ matrix.browser }}