name: Matrix with Cypress
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox, edge, chrome]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: windows-latest
            browser: firefox
          - platform: ubuntu-latest
            browser: edge
          - platform: macos-latest
            browser: firefox
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - name: Running on Platform = ${{ matrix.platform }} Browser = ${{ matrix.browser }}
      run: npx cypress run --browser ${{ matrix.browser }}